### ISSUE TITLE
[FEATURE] Allow unclosed region

### ISSUE THREAD

**Issue by KrosFire** [amber-lang/heraclitus#56]
It would be very usefull for lexer to not throw an error when some defined region is left unclosed.

It's not always required in every lang to have every region closed and it would be usefull to handle it somewhat different

**Comment by Ph0enixKM** [comment]
isn't `allow_left_open` enough? Perhaps it should be changed to `allow_unclosed_region` so that it makes more sense to developers?

**Comment by KrosFire** [comment]
That's IT. Maybe change the name, because at least to me it was not do obvious
